[tool.poetry]
name = "websocket-bot"
version = "0.1.0"
description = ""
authors = ["ShowierData9978 <mellfang36@outlook.com>"]

[tool.poetry.dependencies]
python = "^3.10"
meowerbot = "^1.4.0"
Flask = "^2.2.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
